-- Generated by Stylix
local colors = {
    background = "#151515",
    foreground = "#d0d0d0",
    primary = "#6a9fb5",
    secondary = "#aa759f",
    alert = "#ac4142",

    base00 = "#151515",
    base01 = "#202020",
    base02 = "#303030",
    base03 = "#505050",
    base04 = "#b0b0b0",
    base05 = "#d0d0d0",
    base06 = "#e0e0e0",
    base07 = "#f5f5f5",
    base08 = "#ac4142",
    base09 = "#d28445",
    base0A = "#f4bf75",
    base0B = "#90a959",
    base0C = "#75b5aa",
    base0D = "#6a9fb5",
    base0E = "#aa759f",
    base0F = "#8f5536",
}

return colors
